In [6]:
import pandas as pd

# los datos de las tablas han sido filtrados en clase

In [7]:
sk  = pd.read_csv('sakila.csv')
sk.head()

,customer_id,first_name,last_name,email,active,address,district,postal_code,city,country,rental_date,return_date,amount,payment_date,rental_duration
0,130,charlotte,hunter,charlotte.hunter@sakilacustomer.org,1,758 junan lane,gois,82639,águas lindas de goiás,brazil,2005-05-24 22:53:30,2005-05-26 22:04:30,2.99,2005-05-24 22:53:30,2
1,459,tommy,collazo,tommy.collazo@sakilacustomer.org,1,76 kermanshah manor,esfahan,23343,qomsheh,iran,2005-05-24 22:54:33,2005-05-28 19:40:33,2.99,2005-05-24 22:54:33,4
2,408,manuel,murrell,manuel.murrell@sakilacustomer.org,1,692 amroha drive,northern,35575,jaffna,sri lanka,2005-05-24 23:03:39,2005-06-01 22:12:39,3.99,2005-05-24 23:03:39,8
3,333,andrew,purdy,andrew.purdy@sakilacustomer.org,1,431 székesfehérvár avenue,baki,57828,baku,azerbaijan,2005-05-24 23:04:41,2005-06-03 01:43:41,4.99,2005-05-24 23:04:41,10
4,222,delores,hansen,delores.hansen@sakilacustomer.org,1,810 palghat (palakkad) boulevard,jaroslavl,73431,jaroslavl,russian federation,2005-05-24 23:05:21,2005-06-02 04:33:21,6.99,2005-05-24 23:05:21,9

# tabla catalogo

In [8]:
ca  = pd.read_csv('catalogo.csv')
ca.head()

,film_id,title,description,length,rating,language,category_id,category,inventory_id
0,19,amadeus holy,a emotional display of a pioneer and a technic...,113,PG,english,1,action,93.0
1,19,amadeus holy,a emotional display of a pioneer and a technic...,113,PG,english,1,action,94.0
2,19,amadeus holy,a emotional display of a pioneer and a technic...,113,PG,english,1,action,95.0
3,19,amadeus holy,a emotional display of a pioneer and a technic...,113,PG,english,1,action,96.0
4,19,amadeus holy,a emotional display of a pioneer and a technic...,113,PG,english,1,action,97.0

# tabla de elenco

In [9]:
el = pd.read_csv('elecnco.csv')
el

,film_id,title,actor_id,first_name_clean,last_name_clean,actor_full_name
0,1,ACADEMY DINOSAUR,1,penelope,guiness,penelope guiness
1,23,ANACONDA CONFESSIONS,1,penelope,guiness,penelope guiness
2,25,ANGELS LIFE,1,penelope,guiness,penelope guiness
3,106,BULWORTH COMMANDMENTS,1,penelope,guiness,penelope guiness
4,140,CHEAPER CLYDE,1,penelope,guiness,penelope guiness
...,...,...,...,...,...,...
995,168,COMANCHEROS ENEMY,39,goldie,brody,goldie brody
996,203,DAISY MENAGERIE,39,goldie,brody,goldie brody
997,222,DESERT POSEIDON,39,goldie,brody,goldie brody
998,290,EVERYONE CRAFT,39,goldie,brody,goldie brody
999,293,EXORCIST STING,39,goldie,brody,goldie brody